#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but says "Hi" on the 9th iteration

i=1
while [ $i -le 10 ]
do
    if [ $i -eq 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i++))
done
