#!/usr/bin/env bash
# This script displays the content of the current directory (part after first dash)

for file in *
do
    if [[ -f "$file" && ! "$file" =\~ ^\. ]]
    then
        echo "${file#*-}"
    fi
done
